// Generated by LiveScript 1.5.0
/**
 * @package Detox DHT
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  var fs, gulp, runSequence;
  fs = require('fs');
  gulp = require('gulp');
  runSequence = require('run-sequence');
  require('build-gbu')('src/index.js', 'detox_dht', 'detox-dht.browser', ['debug', 'simple-sha1', 'simple-peer'], {
    task: function(task, dependencies, func){
      if (dependencies && func) {
        dependencies = [];
      }
      if (task !== 'build') {
        gulp.task(task, dependencies, func);
      }
      return this;
    }
  });
  gulp.task('fix-bittorrent-dht', function(){
    var js;
    js = fs.readFileSync("dist/detox-dht.browser.js", {
      encoding: 'utf8'
    });
    js = js.replace("require('debug')('bittorrent-dht')", 'function () {}');
    fs.writeFileSync("dist/detox-dht.browser.js", js);
  }).task('build', function(){
    runSequence('clean', 'browserify', 'fix-bittorrent-dht', 'minify');
  });
}).call(this);
