// Generated by LiveScript 1.5.0
/**
 * @package Detox DHT
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  var bencode, webrtcSocket, webtorrentDht;
  bencode = require('bencode');
  webrtcSocket = require('webtorrent-dht/webrtc-socket');
  webtorrentDht = require('webtorrent-dht');
  module.exports = {
    'bencode': bencode,
    'webrtc-socket': webrtcSocket,
    'webtorrent-dht': webtorrentDht
  };
}).call(this);
